apiVersion: v1
kind: Service
metadata:
  name: alfi-frontend
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: alfi-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80